mappings:
  ApiKeyMemberExtension: Sminnee\ApiKey\ApiKeyMemberExtension
  ApiKeyRequestMiddleware: Sminnee\ApiKey\ApiKeyRequestMiddleware
  GridFieldAddApiKeyButton: Sminnee\ApiKey\GridFieldAddApiKeyButton
  MemberApiKey: Sminnee\ApiKey\MemberApiKey
